-- MySQL Script generated by MySQL Workbench
-- Tue Jul 30 18:11:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myfinances
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myfinances
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myfinances` DEFAULT CHARACTER SET utf8 ;
USE `myfinances` ;

-- -----------------------------------------------------
-- Table `myfinances`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinances`.`user` (
  `id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC)
);


-- -----------------------------------------------------
-- Table `myfinances`.`wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinances`.`wallet` (
  `id_wallet` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `balance` FLOAT NOT NULL,
  `currency` VARCHAR(45) NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_wallet`, `user_id_user`),
  UNIQUE INDEX `id_wallet_UNIQUE` (`id_wallet` ASC),
  INDEX `fk_wallet_user1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_wallet_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `myfinances`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



-- -----------------------------------------------------
-- Table `myfinances`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinances`.`category` (
  `id_category` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC)
);


-- -----------------------------------------------------
-- Table `myfinances`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinances`.`transaction` (
  `id_transaction` INT NOT NULL,
  `amount` FLOAT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `category_id_category` INT NOT NULL,
  `wallet_id_wallet` INT NOT NULL,
  `wallet_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_transaction`, `category_id_category`, `wallet_id_wallet`, `wallet_user_id_user`),
  UNIQUE INDEX `id_transaction_UNIQUE` (`id_transaction` ASC),
  INDEX `fk_transaction_category_idx` (`category_id_category` ASC),
  INDEX `fk_transaction_wallet1_idx` (`wallet_id_wallet` ASC, `wallet_user_id_user` ASC),
  CONSTRAINT `fk_transaction_category`
    FOREIGN KEY (`category_id_category`)
    REFERENCES `myfinances`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_wallet1`
    FOREIGN KEY (`wallet_id_wallet` , `wallet_user_id_user`)
    REFERENCES `myfinances`.`wallet` (`id_wallet` , `user_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table `myfinances`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myfinances`.`statistics` (
  `id_statistics` INT NOT NULL,
  `time_period` DATETIME NOT NULL,
  `total_income` FLOAT NOT NULL,
  `total_expense` FLOAT NOT NULL,
  `balance` FLOAT NOT NULL,
  `user_id_user` INT NOT NULL,
  `wallet_id_wallet` INT NOT NULL,
  `wallet_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_statistics`, `user_id_user`, `wallet_id_wallet`, `wallet_user_id_user`),
  UNIQUE INDEX `idstatistics_UNIQUE` (`id_statistics` ASC),
  INDEX `fk_statistics_user1_idx` (`user_id_user` ASC),
  INDEX `fk_statistics_wallet1_idx` (`wallet_id_wallet` ASC, `wallet_user_id_user` ASC),
  CONSTRAINT `fk_statistics_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `myfinances`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statistics_wallet1`
    FOREIGN KEY (`wallet_id_wallet` , `wallet_user_id_user`)
    REFERENCES `myfinances`.`wallet` (`id_wallet` , `user_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
